spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coaching-db
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true