package com.example.fitnesscoach.utils;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@RequiredArgsConstructor
public enum Workouts {
    ARM_DB_ROW("1 Arm DB Row"),
    ARM_LAT_PULL_DOWN("1 Arm Lat Pull Down"),
    KNEELING_DB_PRESS("1/2 Kneeling DB Press"),
    KNEELING_HIP_TO_SHOULDER("1/2 Kneeling Hip to Shoulder"),
    GOBLET_SQUATS("1/4 - 1 Goblet Squats"),
    SQUAT("1/4 - 1 Squat"),
    BENCH_PRESS("1/4-1 Bench Press"),
    FRONT_SQUAT("1/4-1 Front Squat"),
    GOBLET_SQUAT("1/4-1 Goblet Squat"),
    NARROW_BENCH_PRESS("1/4-1 Narrow Bench Press"),
    WIDE_BENCH_PRESS("1/4-1 Wide Bench Press"),
    ARM_LEG_PLANK_ROWS("1-Arm-1-Leg Plank Rows"),
    TWENTY_ONE("21's"),
    THREE_QUARTER_SIT_UP("3/4 Sit-up"),
    THREE_WAY_SHOULDER("3-way Shoulder"),
    FOUR_HUNDRED_M_RUN("400m Run"),
    AB_CRUNCH("Ab Crunch"),
    AB_ROLL_OUT("Ab Roll-out"),
    ACHILLES_STRETCH("Achilles Stretch"),
    ADDUCTOR_STRETCH("Adductor Stretch"),
    ADDUCTOR_STRETCH_BAND("Adductor Stretch with Band"),
    AIR_BIKE("Air Bike"),
    AIR_SQUAT("Air Squat"),
    AIR_SQUATS("Air Squats"),
    ALTERNATE_HEEL_TOUCH("Alternate Heel Touch"),
    ALTERNATE_LEG_RAISES("Alternate leg raises"),
    ALTERNATING_DB_BENCH("Alternating DB Bench"),
    ALTERNATING_HAND_ROPE_SLAMS("Alternating Hand Rope Slams"),
    ALTERNATING_RENEGADE_ROW("Alternating Renegade Row"),
    ALTERNATING_ROPE_UPPERCUTS("Alternating Rope Uppercuts"),
    A_MARCH("A-March"),
    ANKLE_MOBILITY("Ankle Mobility"),
    ANKLING("Ankling"),
    ANKLING_LATERAL_HOPS("Ankling lateral hops"),
    ANY_BICEP("Any Bicep"),
    ANY_TRICEP("Any Tricep"),
    A_REP("A-rep"),
    ARNOLD_PRESS("Arnold Press"),
    AROUND_THE_WORLD("Around the World"),
    A_RUN("A-Run"),
    A_SKIP("A-Skip"),
    ASSAULT_BIKE("Assault Bike"),
    BACK_EXTENSION("Back Extension"),
    BACK_EXTENSIONS("Back Extensions"),
    BACK_NECK_RESISTANCE("Back Neck Resistance"),
    BACK_SQUAT("Back Squat"),
    BACKWARD_SLED_PULL("Backward Sled Pull"),
    BALANCE_BOARD("Balance Board"),
    BALL_HYPEREXTENSION("Ball Hyperextension"),
    BAND_ADDUCTOR_STRETCH("Band Adductor Stretch"),
    BAND_FRONT_RAISE("Band Front Raise"),
    BAND_FRONT_RAISES("Band Front Raises"),
    BAND_KNEE_EXTENSION("Band Knee Extension"),
    BAND_PULL_APART("Band Pull Apart"),
    BAND_PULL_APARTS("Band Pull Aparts"),
    BAND_RESISTED_CROSSOVER_STEP("Band Resisted Crossover Step"),
    BAND_ROTATION("Band Rotation"),
    BAND_SQUAT("Band Squat"),
    BAND_STRETCH("Band Stretch"),
    BAND_TRICEP_EXTENSION("Band Tricep Extension"),
    BANDED_FACE_PULL("Banded Face Pull"),
    BANDED_GOOD_MORNINGS("Banded Good mornings"),
    BANDED_KB_SWINGS("Banded KB Swings"),
    BANDED_WOODCHOP("Banded Woodchop"),
    BAR_HANG("Bar Hang"),
    BB_BICEP_CURL("BB Bicep Curl"),
    BB_CURL("BB Curl"),
    BB_CURL_CLOSE_GRIP("BB Curl - Close Grip"),
    BB_CURL_WIDE_GRIP("BB Curl - Wide Grip"),
    BB_DEADLIFT("BB Deadlift"),
    BB_FLOOR_PRESS("BB Floor Press"),
    BB_GLUTE_BRIDGE("BB Glute Bridge"),
    BB_JUMP_SQUAT("BB Jump Squat"),
    BB_LUNGE("BB Lunge"),
    BB_NARROW_GRIP_BICEP_CURL("BB Narrow Grip Bicep Curl"),
    BB_OH_PRESS("BB OH Press"),
    BB_OVERHEAD_PRESS("BB Overhead Press"),
    BB_PRONE_CURL("BB Prone Curl"),
    BB_PRONE_CURLS("BB Prone Curls"),
    BB_PRONE_ROW("BB Prone Row"),
    BB_SHOULDER_PRESS("BB Shoulder Press"),
    BB_SHRUG("BB Shrug"),
    BB_SHRUG_BEHIND_BACK("BB Shrug - Behind Back"),
    BB_SHRUG_BEHIND_BACK_2("BB Shrug Behind Back"),
    BB_UPRIGHT_ROW("BB Upright Row"),
    BB_WIDE_GRIP_BICEP_CURL("BB Wide Grip Bicep Curl"),
    BEAR_CRAWL("Bear Crawl"),
    BENCH_DIPS("Bench Dips"),
    BENCH_PRESS("Bench Press"),
    BENCH_PRESS_NARROW_GRIP("Bench Press - Narrow Grip"),
    BENCH_PRESS_WIDE_GRIP("Bench Press - Wide Grip"),
    BENCH_PRESS_WITH_BANDS("Bench Press with Bands"),
    BENCH_PRESS_WITH_CHAINS("Bench Press with Chains"),
    BENCH_PULL("Bench Pull"),
    BENT_OVER_ROW("Bent Over Row"),
    BENT_ARM_BB_PULLOVER("Bent-Arm BB Pullover"),
    BENT_ARM_DB_PULLOVER("Bent-Arm DB Pullover"),
    BICYCLE_CRUNCH("Bicycle Crunch"),
    BIRD_DOG("Bird-dog"),
    BLOCK_PRESS("Block Press"),
    B_MARCH("B-March"),
    BOAT_POSE("Boat Pose"),
    BOSU_BALL_BALANCE("Bosu Ball Balance"),
    BOSU_BALL_BURPEES("Bosu Ball Burpees"),
    BOSU_BALL_SQUAT("Bosu Ball Squat"),
    BOTTOMS_UP_KB_PRESS("Bottoms-up KB Press"),
    BOX_GLUTE_STRETCH("Box Glute stretch"),
    BOX_JUMP("Box Jump"),
    BOX_JUMP_FROM_SEATED("Box Jump From Seated"),
    BOX_SQUAT("Box Squat"),
    BOX_SQUAT_TO_BOX_JUMP("Box Squat-to-Box Jump"),
    BRACED_CORE_SITUP("Braced-Core Sit-up"),
    BRIDGE("Bridge"),
    BROAD_JUMP("Broad Jump"),
    BROAD_JUMP_TO_SPRINT("Broad Jump to Sprint"),
    B_RUN("B-Run"),
    B_SKIP("B-Skip"),
    BULGARIAN_SPLIT_SQUAT("Bulgarian Split Squat"),
    BULGARIAN_SQUAT("Bulgarian Squat"),
    BUNNY_HOPS("Bunny Hops"),
    BURPEE("Burpee"),
    BURPEE_WITH_TUCK_JUMP("Burpee with Tuck Jump"),
    BUTTERFLY_POSE("Butterfly Pose"),
    CABLE_BICEP_CURL("Cable Bicep Curl"),
    CABLE_CHEST_PRESS("Cable Chest Press"),
    CABLE_CROSSOVER("Cable Crossover"),
    CABLE_CRUNCH("Cable Crunch"),
    CABLE_FLYES("Cable Flyes"),
    CABLE_HAMMER_CURL("Cable Hammer Curl"),
    CABLE_IRON_CROSS("Cable Iron Cross"),
    CABLE_PULLDOWN("Cable Pulldown"),
    CABLE_REAR_DELT_FLYES("Cable Rear Delt Flyes"),
    CABLE_ROW("Cable Row"),
    CABLE_SHOULDER_PRESS("Cable Shoulder Press"),
    CABLE_SHRUGS("Cable Shrugs"),
    CABLE_TRICEP_EXTENSION("Cable Tricep Extension"),
    CABLE_UPRIGHT_ROW("Cable Upright Row"),
    CALF_PRESS("Calf Press"),
    CALF_RAISES("Calf Raises"),
    CALF_STRETCH("Calf Stretch"),
    CALIFORNIA_PRESS("California Press"),
    CAT_COW_POSE("Cat-Cow Pose"),
    CHILDS_POSE("Child's Pose"),
    CHILDS_POSE_WITH_BLOCK("Child's Pose with Block"),
    CHINS("Chins"),
    CHIN_UP("Chin-up"),
    CLAMS("Clams"),
    CLAP_PRESS_UP("Clap Press-up"),
    CLAP_PUSH_UP("Clap Push up"),
    CLEAN("Clean"),
    CLEAN_AND_JERK("Clean and Jerk"),
    CLEAN_DEADLIFT("Clean Deadlift"),
    CLOSE_GRIP_DB_BENCH_PRESS("Close Grip DB Bench Press"),
    CLOSE_GRIP_PULL_DOWN("Close-Grip Pull Down"),
    C_MARCH("C-March"),
    CMJ("CMJ"),
    COBRA("Cobra"),
    COPENHAGEN_SIDE_PLANK("Copenhagen Side Plank"),
    CRAB_CRAWL("Crab Crawl"),
    CRAB_WALK("Crab Walk"),
    C_RUN("C-Run")
    CRUNCH("Crunch"),
    CRUNCHES("Crunches"),
    C_SKIP("C-Skip"),
    CUBAN_PRESS("Cuban Press"),
    CUBAN_ROTATION("Cuban Rotation"),
    DB_ALT_BICEP_CURL("DB Alternate Bicep Curl"),
    DB_ALT_CURLS("DB Alternate Curls"),
    DB_ALT_SIDE_BEND("DB Alternating Side Bend"),
    DB_BENCH_PRESS("DB Bench Press"),
    DB_BENCH_PRESS_HAMMER_GRIP("DB Bench Press - Hammer Grip"),
    DB_BENT_OVER_ROW("DB Bent Over Row"),
    DB_BENT_OVER_ROW_HAMMER_GRIP("DB Bent Over Row - Hammer Grip"),
    DB_BICEP_CURL("DB Bicep Curl"),
    DB_CURL("DB Curl"),
    DB_CURL_SEATED("DB Curl - Seated"),
    DB_CURL_PRESS("DB Curl and Press"),
    DB_FLOOR_PRESS("DB Floor Press"),
    DB_FLYES("DB Flyes"),
    DB_HAMMER_CURL_PRESS("DB Hammer Curl and Press"),
    DIAMOND_PUSH_UPS("Diamond Push-ups"),
    DIPS("Dips"),
    DOG("Dog"),
    DOLPHIN_POSE("Dolphin Pose"),
    DOT_DRILL("Dot Drill"),
    DOUBLE_UNDERS("Double Unders"),
    DOWEL_SHOULDER_STRETCH("Dowel Shoulder Stretch"),
    DOWEL_STRETCH("Dowel Stretch"),
    DOWNWARD_FACING_DOG("Downward Facing Dog"),
    DROP_JUMP("Drop jump"),
    DROP_JUMP_HURDLES("Drop Jump Hurdles"),
    DROP_JUMP_BOX_JUMP("Drop Jump to Box Jump"),
    DUCK_WALK("Duck Walk"),
    DYNAMIC_LUNGES("Dynamic Lunges"),
    ECC_CALF_RAISES("Eccentric Calf Raises"),
    ECC_CHIN_UP("Eccentric Chin-up"),
    ECC_EXT_STRENGTHENING("Eccentric Extensor Strengthening"),
    ECC_FRONT_SQUAT("Eccentric Front Squat"),
    ECC_HAMSTRING_CURLS("Eccentric Hamstring Curls"),
    ECC_WIDE_GRIP_PULL_UP("Eccentric Wide Grip Pull-up"),
    ELBOW_TO_KNEE("Elbow to Knee"),
    ELEV_GLUTE_BRIDGE("Elevated Glute Bridge"),
    ELEV_SL_GLUTE_BRIDGE("Elevated SL Glute Bridge"),
    EXERCISE_BIKE("Exercise Bike"),
    EXPLOSIVE_LUNGE("Explosive Lunge"),
    EXTERNAL_ROTATION("External Rotation"),
    FACE_PULL("Face Pull"),
    FARMERS_WALK("Farmers Walk"),
    FAST_TRAP_BAR_LIFTS("Fast Trapbar Lifts"),
    FAT_BAR_BICEP_CURL("Fat Bar Bicep Curl"),
    FAT_BAR_CURLS("Fat Bar Curls"),
    FAT_BAR_PUSH_PRESS("Fat Bar Push Press"),
    FEET_BANDED_DEAD_BUG("Feet Banded Dead Bug"),
    FINISHER("Finisher"),
    FOAM_ROLL("Foam Roll"),
    FOAM_ROLL_CALVES("Foam Roll Calves"),
    FOAM_ROLL_GLUTES("Foam Roll Glutes"),
    FOAM_ROLL_GROIN("Foam Roll Groin"),
    FOAM_ROLL_ITB("Foam Roll ITB"),
    FOAM_ROLL_LATS("Foam Roll Lats"),
    FOAM_ROLL_LOWER_BACK("Foam Roll Lower Back"),
    FOAM_ROLL_QUADS("Foam Roll Quads"),
    FOAM_ROLL_UPPER_BACK("Foam Roll Upper Back"),
    FOREARM_CURL("Forearm Curl"),
    FORWARD_FOLD_CLASP("Forward Fold with Clasp"),
    FORWARD_LUNGE("Forward Lunge"),
    FORWARD_LUNGE_TWIST("Forward Lunge with Twist"),
    FROG_STAND_BALANCE("Frog Stand Balance"),
    FRONT_CRAWL("Front Crawl"),
    FRONT_NECK_RESISTANCE("Front Neck Resistance"),
    FRONT_PLATE_RAISE("Front Plate Raise"),
    FRONT_RACK_LUNGE("Front Rack Lunge"),
    FRONT_RAISE("Front Raise"),
    FRONT_RAISE_AND_PULLOVER("Front Raise and Pullover"),
    FRONT_SQUAT("Front Squat"),
    FULL_BODY_CRUNCH("Full Body Crunch"),
    GLUTE_BRIDGE("Glute Bridge"),
    GLUTE_BRIDGE_HAMSTRING_WALKOUT("Glute Bridge Hamstring Walkout"),
    GLUTE_BRIDGE_HOLD("Glute Bridge Hold"),
    GLUTE_HAM_RAISE("Glute Ham Raise"),
    GLUTE_HIP_LIFTS("Glute Hip Lifts"),
    GLUTE_KICKBACK("Glute Kickback"),
    GLUTE_RAISE("Glute Raise"),
    GLUTE_STRETCH("Glute Stretch"),
    GOBLET_SQUATS("Goblet Squats"),
    GOOD_MORNING("Good Morning"),
    GOOD_MORNINGS("Good Mornings"),
    GORILLA_MOVES("Gorilla Moves"),
    GRAPPLER_HIP_TO_HIP_ROPE_TOSS("Grappler Hip-to-Hip Rope Toss"),
    GROIN_STRETCH("Groin Stretch"),
    HACK_SQUAT("Hack Squat"),
    HALF_KNEELING_BOTTOMS_UP_KB_PRESS("Half Kneeling Bottoms-up KB Press"),
    HALF_KNEELING_CABLE_ROW("Half Kneeling Cable Row"),
    HALF_KNEELING_DB_CURL_AND_PRESS("Half Kneeling DB Curl and Press"),
    HALF_KNEELING_DB_PRESS("Half Kneeling DB Press"),
    HALF_KNEELING_HIP_TO_SHOULDER("Half Kneeling Hip to Shoulder"),
    HALF_KNEELING_WOODCHOP("Half Kneeling Woodchop"),
    HAMMER_CURL("Hammer Curl"),
    HAMMER_GRIP_CHIN_UP("Hammer Grip Chin-up"),
    HAMSTRING_BRIDGE("Hamstring Bridge")





    }
